pink_bin/inverse $1 temp_absdsdsesdsdsedagnvzakbvalbfpa
./Dilatation temp_absdsdsesdsdsedagnvzakbvalbfpa $2 temp_absdsdsesdsdsedagnvzakbvalbfpa_inv
pink_bin/inverse temp_absdsdsesdsdsedagnvzakbvalbfpa_inv $3
rm temp_absdsdsesdsdsedagnvzakbvalbfpa
rm temp_absdsdsesdsdsedagnvzakbvalbfpa_inv
